version: '2'
services:
  geonetwork:
    image: geonetwork:4.2.2
    restart: always
    ports:
      - 7387:8080
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200
    volumes:
      - /var/opt/geonetwork_volumes:/catalogue/data
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
      xpack.security.enabled: "false"
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /var/opt/elasticsearch_volume:/usr/share/elasticsearch/data