version: '2'
services:
  geonetwork:
    image: geonetwork:postgres
    restart: always
    ports:
      - 7387:8080
    environment:
      DATA_DIR: /var/lib/geonetwork_data

      POSTGRES_DB_HOST: ...
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: geonetwork
      POSTGRES_DB_PASSWORD: ...

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200
    volumes:
      - /var/opt/geonetwork_volumes:/var/lib/geonetwork_data
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
      xpack.security.enabled: "false"
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /var/opt/elasticsearch_volume:/usr/share/elasticsearch/data
